addons:
  postgresql: "9.3"
  code_climate:
    repo_token: d8a77be686115a12ef6535d0c507b965b0b22708066fde4d33a6e6a683e8807f

language: ruby
cache: bundler

before_install:
  - sudo apt-get update
  - sudo apt-get install postgresql-contrib-9.3

before_script:
  - cp config/database.yml.travis config/database.yml
  - cp config/initializers/secret_token.rb{.example,}
